import type { Metadata } from "next";
import { PageHero } from "../components/PageHero";
import { SiteFooter } from "../components/SiteFooter";

export const metadata: Metadata = { title: "Carreiras" };

const benefits = ["Participação em projetos reais", "Contacto com diferentes setores", "Desenvolvimento profissional", "Ambiente de aprendizagem", "Mobilidade interna", "Cultura de colaboração", "Impacto no mercado"];
const areas = ["Desenvolvimento de software", "Infraestrutura e sistemas", "Produto", "UI/UX Design", "Design gráfico", "Marketing e comunicação", "Comercial", "Finanças", "Operações", "Recursos Humanos", "Compliance", "Atendimento ao cliente"];

export default function CareersPage() {
  return <main><PageHero eyebrow="Carreiras" index="05 — 06" title="Encontre o seu lugar no que estamos a construir." description="Faça parte de um grupo onde diferentes empresas, áreas e desafios criam espaço para aprender, contribuir e evoluir." /><section className="content-section shell"><div className="section-heading"><div><span className="eyebrow">Porquê o Grupo JC</span><h2>Um lugar para fazer, aprender e crescer.</h2></div><p>Cada empresa abre contacto com novos desafios, equipas e contextos de aprendizagem.</p></div><div className="benefit-grid">{benefits.map((benefit, index) => <article key={benefit}><span>{String(index + 1).padStart(2,"0")}</span><h3>{benefit}</h3></article>)}</div></section><section className="career-areas"><div className="shell content-grid"><div className="section-aside"><span className="section-number">Áreas</span></div><div className="content-main"><h2>Competências diferentes. O mesmo espaço para evoluir.</h2><div className="career-area-list">{areas.map((area, index) => <span key={area}><i>{String(index + 1).padStart(2,"0")}</i>{area}</span>)}</div></div></div></section><section id="jovens" className="young-talent shell"><div className="young-symbol"><span>1º</span><i /></div><div><span className="eyebrow">Jovens talentos</span><h2>O primeiro passo pode começar aqui.</h2><p>Criamos oportunidades para jovens profissionais ganharem experiência, desenvolverem competências e participarem em projetos relevantes.</p><div className="chip-list">{["Estágios profissionais", "Programa de trainees", "Academia tecnológica", "Workshops", "Mentoria", "Bolsas de formação"].map((item) => <span className="chip" key={item}>{item}</span>)}</div></div></section><section id="candidatura" className="application-cta"><div className="shell"><span className="eyebrow">Candidatura espontânea</span><h2>Não encontrou a oportunidade certa?</h2><p>Envie o seu perfil para a nossa base de talentos. O canal de candidatura será disponibilizado com a publicação das primeiras oportunidades.</p><button type="button" className="button button--dark" disabled>Canal em preparação</button></div></section><SiteFooter /></main>;
}
