INSERT INTO `categories` (`name`, `slug`) VALUES
  ('Grupo JC', 'grupo-jc'),
  ('Tecnologia', 'tecnologia'),
  ('Pessoas', 'pessoas'),
  ('Impacto', 'impacto'),
  ('Empresas', 'empresas'),
  ('Parcerias', 'parcerias');
--> statement-breakpoint
INSERT INTO `posts` (
  `slug`, `title`, `excerpt`, `content`, `category_id`, `status`,
  `reading_minutes`, `published_at`, `created_at`, `updated_at`, `art`
) VALUES
  ('uma-estrutura-criada-para-ligar-diferentes-forcas', 'Uma estrutura criada para ligar diferentes forças', 'O Grupo JC nasce para aproximar empresas, competências e oportunidades sob uma visão comum.', 'Reunimos negócios com vocações distintas e uma ambição partilhada: criar soluções úteis para pessoas, empresas e para o desenvolvimento de Angola.\n\nO Grupo JC reúne empresas que actuam em áreas estratégicas, da tecnologia e pagamentos ao entretenimento digital. A sua força está na combinação de perspectivas, competências e experiências que se complementam.\n\nEsta estrutura permite que cada empresa mantenha a sua identidade e especialização, beneficiando simultaneamente de uma visão comum, de conhecimento partilhado e de uma capacidade maior para criar valor.\n\n## Uma visão que liga competências\n\nAcreditamos que os desafios mais relevantes exigem colaboração. Por isso, aproximamos equipas, tecnologia e conhecimento do mercado para construir respostas mais consistentes e preparadas para evoluir.\n\nMais do que um conjunto de empresas, o Grupo JC é um ecossistema orientado para transformar potencial em progresso.', (SELECT `id` FROM `categories` WHERE `slug` = 'grupo-jc'), 'published', 4, '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z', 'network'),
  ('solucoes-locais-para-desafios-reais', 'Soluções locais para desafios reais', 'Conhecimento do mercado e capacidade técnica trabalham em conjunto para criar produtos relevantes.', 'A tecnologia ganha valor quando responde ao contexto de quem a utiliza. É desse princípio que partem as soluções desenvolvidas no ecossistema Grupo JC.\n\nDesenvolver tecnologia em Angola pede mais do que conhecimento técnico. Pede escuta, proximidade e uma compreensão clara dos hábitos, necessidades e oportunidades de cada sector.\n\nNas nossas empresas, as equipas procuram transformar esse conhecimento em produtos simples, seguros e úteis para o quotidiano de pessoas e organizações.\n\n## Tecnologia com propósito\n\nDe plataformas de gestão a serviços financeiros digitais, cada solução é pensada para reduzir fricção, melhorar operações e tornar novos serviços mais acessíveis.\n\nA capacidade técnica é essencial, mas é a ligação ao mercado que permite criar experiências verdadeiramente relevantes.', (SELECT `id` FROM `categories` WHERE `slug` = 'tecnologia'), 'published', 3, '2026-05-28T00:00:00.000Z', '2026-05-28T00:00:00.000Z', '2026-05-28T00:00:00.000Z', 'growth'),
  ('talento-que-cresce-enquanto-constroi', 'Talento que cresce enquanto constrói', 'A evolução das empresas também cria espaço para novas experiências, competências e percursos.', 'As pessoas estão no centro de cada empresa do Grupo JC. É através do seu trabalho, curiosidade e ambição que as ideias se tornam soluções concretas.\n\nCrescer profissionalmente é participar em desafios reais, aprender com equipas diversas e assumir responsabilidades com impacto. É essa experiência que procuramos proporcionar a quem trabalha connosco.\n\nValorizamos percursos diferentes e criamos contextos onde a aprendizagem acompanha a evolução dos negócios.\n\n## Construir em conjunto\n\nDa formação à colaboração entre áreas, investimos em ambientes que incentivam a iniciativa, a partilha e a melhoria contínua.\n\nQuando o talento encontra espaço para evoluir, as empresas também ganham a capacidade de ir mais longe.', (SELECT `id` FROM `categories` WHERE `slug` = 'pessoas'), 'published', 3, '2026-05-14T00:00:00.000Z', '2026-05-14T00:00:00.000Z', '2026-05-14T00:00:00.000Z', 'people'),
  ('crescer-com-responsabilidade', 'Crescer com responsabilidade', 'Mais do que resultados de negócio, procuramos gerar oportunidades que acompanham o mercado.', 'Para o Grupo JC, crescimento significa criar soluções sustentáveis, gerar emprego e tornar serviços importantes mais próximos das pessoas.\n\nA nossa actuação procura conciliar ambição empresarial com responsabilidade. Cada negócio deve ser capaz de gerar valor duradouro para clientes, equipas, parceiros e para as comunidades onde está presente.\n\nEste compromisso traduz-se na forma como desenvolvemos produtos, criamos oportunidades de trabalho e investimos no crescimento de pessoas e empresas.\n\n## Impacto que se multiplica\n\nQuando uma solução simplifica uma operação ou aproxima um serviço essencial, cria efeitos que vão além da transacção. Ajuda pessoas e organizações a avançar com mais autonomia.\n\nÉ essa visão de impacto prático que orienta as escolhas do Grupo JC.', (SELECT `id` FROM `categories` WHERE `slug` = 'impacto'), 'published', 4, '2026-04-30T00:00:00.000Z', '2026-04-30T00:00:00.000Z', '2026-04-30T00:00:00.000Z', 'impact'),
  ('seis-especializacoes-um-ecossistema', 'Seis especializações, um ecossistema', 'Conheça as diferentes frentes que formam o portefólio do Grupo JC.', 'Cada empresa responde a necessidades específicas. Juntas, formam uma presença mais ampla em sectores que ajudam a transformar o mercado angolano.\n\nO portefólio do Grupo JC reúne competências em pagamentos, serviços financeiros, tecnologia e entretenimento digital. Esta diversidade permite-nos acompanhar diferentes momentos da vida das pessoas e da operação das empresas.\n\nA independência de cada marca é um activo: garante foco, especialização e uma relação mais directa com o seu público.\n\n## Especialização que cria valor\n\nA relação entre as empresas cria oportunidades de colaboração sem diluir aquilo que torna cada uma única. É desta combinação que nasce um ecossistema mais preparado para responder a desafios complexos.', (SELECT `id` FROM `categories` WHERE `slug` = 'empresas'), 'published', 3, '2026-04-16T00:00:00.000Z', '2026-04-16T00:00:00.000Z', '2026-04-16T00:00:00.000Z', 'portfolio'),
  ('novas-possibilidades-comecam-com-uma-conversa', 'Novas possibilidades começam com uma conversa', 'O grupo está aberto a ligações que ajudem empresas, instituições e pessoas a avançar.', 'A colaboração é uma das formas mais directas de transformar uma boa ideia numa solução com alcance real.\n\nProcuramos parcerias que combinem propósito, conhecimento e capacidade de execução. Podem nascer de uma necessidade concreta, de uma oportunidade de inovação ou de uma vontade partilhada de criar impacto.\n\nO nosso ecossistema está disponível para dialogar com empresas, instituições e profissionais que acreditam no potencial da colaboração.\n\n## Vamos construir\n\nCada ligação começa por compreender bem o desafio. A partir daí, podemos desenhar caminhos e soluções que façam sentido para todos os envolvidos.', (SELECT `id` FROM `categories` WHERE `slug` = 'parcerias'), 'published', 2, '2026-04-02T00:00:00.000Z', '2026-04-02T00:00:00.000Z', '2026-04-02T00:00:00.000Z', 'partnership');
