import type { Metadata } from "next";
import { PageHero } from "../components/PageHero";
import { SiteFooter } from "../components/SiteFooter";

export const metadata: Metadata = { title: "Impacto" };

const pillars = [
  { index: "01", title: "Criar empresas também é criar oportunidades", label: "Emprego", text: "Geramos espaço para novas carreiras, crescimento interno e mobilidade entre diferentes empresas e áreas do grupo.", items: ["Empregos diretos", "Oportunidades em diferentes áreas", "Desenvolvimento de carreiras", "Crescimento interno", "Mobilidade entre empresas"] },
  { index: "02", title: "Preparar talento para os desafios do futuro", label: "Jovens", text: "A primeira experiência profissional pode tornar-se o início de uma carreira com propósito, aprendizagem e impacto.", items: ["Programas de estágio", "Formação profissional", "Mentoria", "Workshops", "Parcerias com instituições de ensino", "Competências digitais"] },
  { index: "03", title: "Soluções criadas a partir da nossa realidade", label: "Tecnologia local", text: "Valorizamos equipas locais e conhecimento do mercado para responder a necessidades específicas com tecnologia relevante.", items: ["Produtos desenvolvidos localmente", "Conhecimento do mercado", "Valorização de profissionais nacionais", "Propriedade intelectual", "Resposta a necessidades reais"] },
];

export default function ImpactPage() {
  return <main><PageHero eyebrow="Impacto" index="04 — 06" title="O nosso crescimento deve gerar mais oportunidades." description="Acreditamos que empresas relevantes também devem contribuir para o desenvolvimento das pessoas, das organizações e do mercado em que atuam." /><section className="impact-pillars shell">{pillars.map((pillar) => <article key={pillar.index}><div className="impact-pillar-meta"><span>{pillar.index}</span><strong>{pillar.label}</strong></div><div><h2>{pillar.title}</h2><p>{pillar.text}</p><div className="chip-list">{pillar.items.map((item) => <span className="chip" key={item}>{item}</span>)}</div></div></article>)}</section><section className="impact-data"><div className="shell"><div className="section-heading section-heading--light"><div><span className="eyebrow eyebrow--light">Medir para evoluir</span><h2>Indicadores que tornam o impacto visível.</h2></div><p>A plataforma está preparada para receber dados reais e atualizáveis à medida que os indicadores forem consolidados.</p></div><div className="impact-data-grid">{["Colaboradores", "Jovens formados", "Estagiários integrados", "Produtos lançados", "Clientes atendidos", "Empresas parceiras", "Transações processadas", "Regiões alcançadas"].map((item, index) => <article key={item}><span>{String(index + 1).padStart(2,"0")}</span><strong>—</strong><p>{item}</p></article>)}</div></div></section><section className="content-section shell"><div className="content-grid"><div className="section-aside"><span className="section-number">Histórias</span></div><div className="content-main"><h2>O impacto também se conta através de pessoas.</h2><p className="prose-large">Em breve, esta área reunirá histórias reais de colaboradores, jovens talentos, equipas e empresas transformadas pelos projetos do Grupo JC.</p></div></div></section><SiteFooter /></main>;
}
